### ISSUE TITLE
Feature Request: systemMessage

### ISSUE THREAD

**Issue by Erisfiregamer1** [waylaidwanderer/node-chatgpt-api#178]
Allow us to set the system message sent to Bing Chat! What if I want my chatbot to be named "Jake"?

**Comment by waylaidwanderer** [comment]
While this is possible, I don't think it'll work consistently due to the way Bing/Sydney's prompt is formatted. Its messages are added to its prompt like this:

```
[Sydney](#message)
<Sydney's message here>
```

Then the prompt ends with, "Write Sydney's response to the user..." so if you try to change the name, it could get confused and refuse to adopt the character, which is why I'm piggybacking off the Sydney character instead.

That's my line of thinking, anyway.
You can clone the repo, try to modify the jailbreak code yourself, and let me know how it works. I'd be interested in your results.

**Comment by KevinKaiwenZheng** [comment]
@waylaidwanderer See #181, I've tried different roles with the injected system prompt and it works well. It seems to me that the idea is feasible and actually works well. That should definitely be a feature request.

**Comment by Erisfiregamer1** [comment]
I'll do it :)

**Comment by Erisfiregamer1** [comment]
#199
