### ISSUE TITLE
Failed to parse response body.

### ISSUE THREAD

**Issue by eeviriyi** [waylaidwanderer/node-chatgpt-api#393]
![image](https://github.com/waylaidwanderer/node-chatgpt-api/assets/110186775/b60e96de-8716-48ee-a9da-a79fa5539a6b)

**Comment by gengituser** [comment]
I have the same problem.  Nothing helps. I've tried to set all the cookies instead of the "_U" cookie in the settings.js, doesn't help. All worked well 3-4 days ago, but now I always get this error. Can someone give any advice please?

**Comment by sforman2861597** [comment]
if you are Chinese
you can try to
删掉BingAIClient.js 中的 'x-forwarded-for' 部分或将这一行注释
然后配置好代理

**Comment by joshholly** [comment]
So it seems like /turing/conversation/create doesn't work anymore. What's also weird is /turing/conversation/create is to create a new conversation and I get this error on existing conversations.

**Comment by waylaidwanderer** [comment]
I would suggest either removing the config cookies key/value entirely or set your entire cookies string, not just the _U cookie. If your IP isn't blocked by Bing, that should resolve this issue.

**Comment by joshholly** [comment]
I did that, same issue. The issue is that turing/conversation/create is no longer a valid path. Please update the code.

**Comment by joshholly** [comment]
I was wrong! I was able to modify the code and use cookies instead of just a token and it worked!

**Comment by waylaidwanderer** [comment]
You don't need to modify the code. It supports setting your cookies instead of just a token already.

**Comment by gengituser** [comment]
> I was wrong! I was able to modify the code and use cookies instead of just a token and it worked!

How did you do that? I think I've done it from the very beginning, but it didn't help.

So I take all the cookies here
![2023-05-31 08_48_36-Window](https://github.com/waylaidwanderer/node-chatgpt-api/assets/63794428/6764a741-5e7e-4a7a-a30b-a1c81b6bb25d)

Add it to my  settings.js

![2023-05-31 08_51_11-Window](https://github.com/waylaidwanderer/node-chatgpt-api/assets/63794428/0f3009fe-5707-4cf3-ad34-06f8c9334d16)

And I get this error on my server:

![2023-05-31 08_55_04-Window](https://github.com/waylaidwanderer/node-chatgpt-api/assets/63794428/ac010f1f-7832-492f-9713-96b961c0bfdf)

And this one as a response to my request:

{"error":"Cannot convert argument to a ByteString because the character at index 2667 has a value of 1042 which is greater than 255."}

**Comment by joshholly** [comment]
I am using chatgpt-clone which uses this as a dependency. So I am not sure how to do it for yours.

**Comment by waylaidwanderer** [comment]
> And I get this error on my server:
@gengituser you probably copy-pasted it manually by selecting the text right? You need to right-click and select the Copy option from the menu instead, as the visible text is truncated in the middle using a special "..." unicode character.

**Comment by gengituser** [comment]
> > And I get this error on my server:
> 
> @gengituser you probably copy-pasted it manually by selecting the text right? You need to right-click and select the Copy option from the menu instead, as the visible text is truncated in the middle using a special "..." unicode character.

I just found a solution thanks to another discussion here: https://github.com/waylaidwanderer/node-chatgpt-api/issues/302

The issue was that I'm not from the English speaking country and my name contains non-English characters. That's why within my cookies there were non-English characters. I just went into my Microsoft account settings and rewrote my name in English. Then I re-logged into Bing search and copied the new cookies. After that, everything worked! )
