### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by transitive-bullshit** [waylaidwanderer/node-chatgpt-api#4]
## Questions

How stable is this for you in general? How many accts are you typically using and how many reqs / hour?
- can you DM me on discord what you're using for residential IP proxy? just curious

## Feedback

- it'd be nice to have the pool functionality available as a module usable outside of this server (stretch goal; not necessary; just a thought)
- right now, the way you're initializing accts, it's hard to know when they're available after one or more `initSession` calls succeeds
- checking the response for [special response strings](https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/chatgpt-api-pool.ts#L381-L407) is important for robustness
- maybe we could just port https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/chatgpt-api-pool.ts? I know you asked me to do this awhile ago, but I never got around to it..
- maybe add support for 2captcha as well as nopecha
- it looks you're periodically running `refreshSession` but never `resetSession`. does this work for you consistently in practice? `ChatGPTAPIBrowser.sendMessage` has some error handling & retry logic, but over time it's gotten pretty messy btwn the logic I have in there vs in the `ChatGPTAPIPool` in my twitter bot. Lots of stuff is duplicated, and it's kind of a mess.
- maybe add an example `curl` or `httpie` example to the readme to show how you're invoking the local API? something people can copy & paste
- conversation ID persistence will be important

## Comments

- I really like the ability to use a proxy per acct

Sorry for the long feedback. I just want to make sure if I'm going to prominently direct people to this project from the `chatgpt-api` repo, that it encapsulates the robustness learnings I've come across from running the twitter bot.

The more feedback I write, the more I think this might not be useful feedback. I dunno; just stream of consciousness.

Cheers && thanks! 🙏 💕 🙏

**Comment by waylaidwanderer** [comment]
> it'd be nice to have the pool functionality available as a module usable outside of this server (stretch goal; not necessary; just a thought)

Yes, I had this idea too, but I wanted to do something simple to start with.

> right now, the way you're initializing accts, it's hard to know when they're available after one or more `initSession` calls succeeds

I didn't see that as a big issue as long as one or more accounts are usable, tbh.

> checking the response for [special response strings](https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/chatgpt-api-pool.ts#L381-L407) is important for robustness

Oh, I somehow thought that your library would handle that and throw an error or something... maybe worth doing something on your end?

> maybe we could just port https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/chatgpt-api-pool.ts? I know you asked me to do this awhile ago, but I never got around to it..

See first response.

> maybe add support for 2captcha as well as nopecha

Actually, since the `account` object is passed directly to your browser class, you can already use 2captcha instead if you want. I'll add a global setting for that as well, similar to NopeCHA. I only had NopeCHA to start with because it's what I use myself.

> it looks you're periodically running `refreshSession` but never `resetSession`. does this work for you consistently in practice? `ChatGPTAPIBrowser.sendMessage` has some error handling & retry logic, but over time it's gotten pretty messy btwn the logic I have in there vs in the `ChatGPTAPIPool` in my twitter bot. Lots of stuff is duplicated, and it's kind of a mess.

I've had it go over 12 hours without any issues, though I haven't tried it for an extended period of time since I've been restarting it while working on the code for this repo.

> maybe add an example `curl` or `httpie` example to the readme to show how you're invoking the local API? something people can copy & paste

Good idea.

> conversation ID persistence will be important

Yeah, I thought I would add an option to write it to some JSON files to start with, then maybe add support for something like Redis etc with a module or something...

@transitive-bullshit Thanks for the feedback 🙏

**Comment by djaffer** [comment]
Yes, if there is a pool with a queue concept this would be golden.

**Comment by waylaidwanderer** [comment]
No longer relevant due to #15, which implements the (leaked) official ChatGPT model via OpenAI's API. Feel free to re-open if the model becomes disabled.

By the way, the v1.0.0 branch supports persistent conversations.
